"""German textfile"""

title = "Nebenkostenabrechnung"
menu_houses = "Häuser"
menu_renters = "Mieter"
menu_adresses = "Adressen"
menu_exit = "Beenden"
button_prev = "Vorheriger"
button_next = "Nächster"
button_new = "Neuer Eintrag"
button_change = "Änderungen übernehmen"
button_delete = "Eintrag löschen"
anrede = "Anrede"
vorname = "Vorame"
nachname = "Nachname"
name = "Name"
anzahl_personen = "Anzahl Personen"
weitere_personen = "Weitere Personen"
strasse = "Straße"
hausnummer = "Hausnummer"
plz = "PLZ"
ort = "Stadt"
land = "Land"
size = "Größe"
id = "ID"
adress = "Adresse"
adress_button = "Adresse ändern"
button_returning = "Auswählen"